#hould spawn three containers here
---
apiVersion: v1
kind: Pod
metadata:
  name: gcpbackendtest
  labels:
    app: gcpbackendtest
spec:
  containers:
    - name: gcpbackend
      image: gcr.io/ziruiz-project0/ziruizgcp:v2
      ports:
       - name: http
         containerPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: gcpbackendtest
spec:
  ports:
  - name: http
    port: 80
    targetPort: 6000
  selector:
    app: gcpbackendtest
  type: LoadBalancer

